const actionTypes = {
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_ERROR : 'LOGIN_ERROR',
    LOG_OUT : 'LOG_OUT',
    GET_CART_SUCCESS : 'GET_CART_SUCCESS',
    GET_CART_FAIL : 'GET_CART_FAIL',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAIL : 'ADD_TO_CART_FAIL',
    QUANTITY_INCREASE_SUCCESS : 'QUANTITY_INCREASE_SUCCESS',
    QUANTITY_INCREASE_FAILED : 'QUANTITY_INCREASE_FAILED',
    QUANTITY_DECREASE_SUCCESS : 'QUANTITY_DECREASE_SUCCESS',
    QUANTITY_DECREASE_FAILED : 'QUANTITY_DECREASE_FAILED',
    DELETE_PRODUCT_CART_SUCCESS : 'DELETE_PRODUCT_CART_SUCCESS',
    DELETE_PRODUCT_CART_FAILED : 'DELETE_PRODUCT_CART_FAILED'
}
export default actionTypes;